### ISSUE TITLE
How do I enable FlashAttention 2 exllama in oobabooga webui?

### ISSUE THREAD

**Issue by ghost** [jllllll/exllama#10]
I noticed that bumps 0.0.8 and 0.0.9 were added thanks to you @jllllll :) 
I have flash attention 2 installed and working on exllama main but how do I enable it for the textgen webui? 

Thank you for your time.

**Comment by jllllll** [comment]
An option for that has not been added yet to the webui as it is considered experimental. You can enable it by adding the setting to
`text-generation-webui\modules\exllama.py` [line 52](https://github.com/oobabooga/text-generation-webui/blob/d06c34dea5dc3abed1bc2df96b9616ec50d1040d/modules/exllama.py#L52C9-L52C63) like so:
```
config.compress_pos_emb = shared.args.compress_pos_emb
config.use_flash_attn_2 = True
```

**Comment by ghost** [comment]
Perfect, thank you!
