### ISSUE TITLE
ImportError: cannot import name 'make_q4' from 'exllama_ext' (unknown location)

### ISSUE THREAD

**Issue by kmf56** [jllllll/exllama#11]
Hello!

Working through a small issue. I just installed this fork of exllama via github clone and installing the reqs.txt. When I try to run the example script, I'm getting this traceback:

![Screenshot 2023-08-02 140359](https://github.com/jllllll/exllama/assets/120470926/33d7e662-920e-4f52-8d14-a2112bb0788c)

Did I miss a step somewhere? Sorry, if this is a dumb ask. I'm super new at this :(

**Comment by jllllll** [comment]
Make sure to install the exllama package with: `python -m pip install .`

This fork's purpose is to provide a separate package for the exllama code that does not rely on JIT compiling at runtime and allows for distributing the code and kernels so that others do not need to build it themselves.

**Comment by kmf56** [comment]
Ah thank you!
