### ISSUE TITLE
Error checking compiler version for cl: [WinError 2]

### ISSUE THREAD

**Issue by abdsrd** [jllllll/exllama#13]
Hello jlllll,

Many thanks for your work.

I am trying to install using python -m pip install git+https://github.com/jllllll/exllama however I get this error message that I cannot solve:

      file exllama.py (for module exllama) not found
      running build_ext
      C:\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] Can't find the specified file
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      error: [WinError 2] Le fichier spécifié est introuvable
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for exllama
  Running setup.py clean for exllama
Failed to build exllama
ERROR: Could not build wheels for exllama, which is required to install pyproject.toml-based projects

It seems that the installer cannot find the specified compiler cl.exe, I've noticed that there is a PR with same issue that has been merged in the main Exllama git : 

https://github.com/turboderp/exllama/pull/36

I would love to use your fork to run some projects locally, any idea how to solve this?

Of course Microsoft Visual Code 2022 has been installed with C++ developpers addon.

Many thanks for your help

**Comment by jllllll** [comment]
`UserWarning: Error checking compiler version for cl` is fairly normal to some degree. However, building usually doesn't fail because of it.

Visual Studio detection can be fairly buggy in general. The only way I've found to get around it is to activate VS's dev cmd before building:
```
call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
```
For Powershell:
```
. 'C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\Launch-VsDevShell.ps1' -Arch amd64
```
Change `BuildTools` to the edition of VS that that you are using. Sometimes a system restart can fix it as well.

As for the PR that you linked, that was largely just for Pytorch's JIT compile which isn't used here. I could implement something similar for this package. However, I would rather not as that isn't how VS is intended to be used and has the potential to break building for other systems.

If you don't mind using a pre-compiled wheel, then they are available in the releases section:
https://github.com/jllllll/exllama/releases/latest

They can be installed directly like so:
```
python -m pip install https://github.com/jllllll/exllama/releases/download/0.0.11/exllama-0.0.11+cu118-cp310-cp310-win_amd64.whl
```

**Comment by abdsrd** [comment]
Installed the pre compiled one ! Many Thanks. Do you have a code exemple of loading a model using Exllama directly through python?

**Comment by jllllll** [comment]
```python
from exllama.model import ExLlama, ExLlamaCache, ExLlamaConfig
from exllama.tokenizer import ExLlamaTokenizer
from exllama.generator import ExLlamaGenerator
from pathlib import Path
import os

# Directory containing model, tokenizer, generator

model_directory =  r"D:\path\to\model\dir"

model_directory = Path(model_directory)

# Locate files we need within that directory

tokenizer_path = model_directory.joinpath("tokenizer.model")
model_config_path = model_directory.joinpath("config.json")
st_pattern = "*.safetensors"
model_path = next(model_directory.glob(st_pattern))

# Create config, model, tokenizer and generator

config = ExLlamaConfig(model_config_path)               # create config from config.json
config.model_path = model_path                          # supply path to model weights file

model = ExLlama(config)                                 # create ExLlama instance and load the weights
tokenizer = ExLlamaTokenizer(str(tokenizer_path))            # create tokenizer from tokenizer model file

cache = ExLlamaCache(model)                             # create cache for inference
generator = ExLlamaGenerator(model, tokenizer, cache)   # create generator

# Configure generator

generator.disallow_tokens([tokenizer.eos_token_id])

generator.settings.token_repetition_penalty_max = 1.2
generator.settings.temperature = 0.95
generator.settings.top_p = 0.65
generator.settings.top_k = 100
generator.settings.typical = 0.5

# Produce a simple generation

prompt = "Once upon a time,"
print (prompt, end = "")

output = generator.generate_simple(prompt, max_new_tokens = 200)

print(output[len(prompt):])
```

**Comment by jllllll** [comment]
That is a modified version of the `example_basic.py` script from the repo that works with Windows paths a bit better.
