### ISSUE TITLE
Strange output 

### ISSUE THREAD

**Issue by ZanMax** [jllllll/exllama#17]
Hello,

I am getting strange outputs running the example_basic.py.

`USER: Tell me a joke ASSISTANT:lia BeautINIT Savficounityyenigo Ash Norman corso курunnel potan Tobuggidiéli Sieg  лоimalune pod MannbookparametersatalieriassetsLENG SETestinitallapolitryptgunazineьюinalȘlanedy Finalalladxatomic nam Finależyób Savallaososстіметlebunity Test SavunicSEE SE girlstxolly gros SE кур Propertyallaья хиallalub�halbnitたrite Asplla SEья ChapterettiLINday Jewпере soll Liturre курnicfit poéroïallaalla sow fitsьяttembergother sm Sav SErizonarite тан SEfireunnCur Tabrite Intliayernneeussen Mart https mur SE курyen курatal(()unity ло курpod vi лоьяimalmatimalсни padre Beautatal owьяptyliaatalimal курьяья Savṇ forgetьяfico course SE Beaut Beautunityзо Beautfico Ven物atal Siegalla LeopoldallaelnINITatalyenigo�igoTransaction кур GirlsINITья ло Sieg`

- OS: Ubuntu 22.04.3 LTS
- GPU: AMD MI60
- Model: TheBloke/WizardLM-7B-uncensored-GPTQ

**Installation steps:**
`
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.6
`
`
python -m pip install git+https://github.com/jllllll/exllama
`
`
pip install -r requirements.txt
`
It all works fine when I run the same model using **text-generation-webui** and exllama.

What am I doing wrong?

**Comment by jllllll** [comment]
Try installing one of the pre-compiled wheels and see if it works better: https://github.com/jllllll/exllama/releases/tag/0.0.18
```
pip3 install https://github.com/jllllll/exllama/releases/download/0.0.18/exllama-0.0.18+rocm5.6-cp310-cp310-linux_x86_64.whl
```
The above command installs the wheel that text-generation-webui uses. Beyond that, I've no idea why it wouldn't work. AMD GPU support is downright messy and there isn't much of anything that can be done about it as ROCm pretty much requires dedicated AMD code for proper AMD GPU support and the code here was written for NVIDIA GPUs.

**Comment by ZanMax** [comment]
The same result.  I think I need to look at text-generation-webui implementation.  
I appreciate your help.
