### ISSUE TITLE
Can you provide the whl of CUDAv11.8?

### ISSUE THREAD

**Issue by jimi202008** [jllllll/exllama#5]
Try to build the whl of CUDAv11.8, but always report an error. Can you provide the whl of CUDAv11.8.
Building wheels for collected packages: exllama
  Building wheel for exllama (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1544 lines of output]

**Comment by jllllll** [comment]
Done: https://github.com/jllllll/exllama/releases/latest
